name: CI

on:
  push:

  workflow_dispatch:
#   set schedule
#   schedule:
#     - cron: '*/5 * * * *'
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "here"
  call:
    uses: ./.github/workflows/new-file.yml
    secrets: inherit