name: CI

on:
  schedule:
    - cron: '52 12 * * *'
    - cron: '53 12 * * 5'
    - cron: '54 15 * * 5'
    

jobs:
  call-other-workflow:
    uses: ./.github/workflows/new-file.yml
    secrets: inherit
