name: CI

on:
  push:
    branches: 
      - '*'
  workflow_dispatch:
  
  schedule:
    - cron: '46 12 * * *'
    

jobs:
  call-other-workflow:
    uses: ./.github/workflows/new-file.yml
    secrets: inherit
