name: read env from another file

on:
  push:
    inputs:
      what:
        type: boolean
        required: true
        default: true
    
  workflow_dispatch:
    inputs:
      what:
        type: boolean
        required: true
        default: true

  workflow_call:
    inputs:
      what:
        type: boolean
        required: true
        default: true

jobs:
  readEnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: write outputs
        run: echo "dev=${{ github.ref_name }}" >> $GITHUB_ENV
      - run: echo ${{ github.events.inputs.what }}
      - run: echo "event=${{ github.event_name }}" >> $GITHUB_ENV
        if: ${{ inputs.what || github.event_name == 'workflow_call'}}
      - run: echo "region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV  
      - name: show outputs
        run: echo ${{ env.dev }}
