name: read env from another file

on:
  workflow_dispatch:

  workflow_call:


jobs:
  readEnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: write outputs
        run: echo "dev=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: show outputs
        if: github.event_name != 'workflow_call'
        run: echo ${{ env.dev }}
