name: read env from another file

on:
  workflow_dispatch:

  workflow_call:


jobs:
  readEnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: write outputs
        run: echo "dev=${{ github.ref_name }}" >> $GITHUB_ENV
      - run: echo "event=${{ github.event_name }}" >> $GITHUB_ENV
      - run: echo ${{ env.event }}
      - run: echo "region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV  
      - name: show outputs
        if: github.event_name == 'pull_request'
        run: echo ${{ env.dev }}
