name: read env from another file

on:
  workflow_dispatch:
    inputs:
      what:
        type: boolean
        required: false
        default: true

  workflow_call:
    inputs:
      what:
        type: boolean
        required: false
        default: true

jobs:
  readEnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: write outputs
        run: echo "dev=${{ github.ref_name }}" >> $GITHUB_ENV
      - run: echo "event=${{ github.event_name }}" >> $GITHUB_ENV
      - run: echo ${{ env.event }}
      - run: echo "region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV  
      - name: show outputs
        if: ${{ github.event.inputs.what != 'true' }}
        run: echo ${{ env.dev }}
